finalproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('studentmanager/', include('studentmanager.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='studentmanager/', permanent=False))
]

studentmanager/urls.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path

from . import views

app_name = 'studentmanager'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('student/', login_required(views.StudentListView.as_view()), name='student'),
    path('student/<int:id>/delete/', login_required(views.StudentDeleteView.as_view()), name='student-delete'),
    path('student/add/', login_required(views.StudentCreateView.as_view()), name='add'),
    path('exam/', login_required(views.ExamListView.as_view()), name='exam'),
    path('exam/add/', login_required(views.ExamCreateView.as_view()), name='exam-add'),
    path('exam/<int:id>/delete/', login_required(views.ExamDeleteView.as_view()), name='exam-delete'),
    path('result/', login_required(views.ResultListView.as_view()), name='result'),
    path('result/add/', login_required(views.ResultCreateView.as_view()), name='result-add'),
    path('result/<int:exam_id>/<int:student_id>/delete', login_required(views.ResultDeleteView.as_view()),
         name='result-delete'),
    path('login/', LoginView.as_view(), {'next_page': settings.LOGIN_REDIRECT_URL}, name='login'),
    path('logout/', LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
]

studentmanager/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.urls import reverse


class Student(models.Model):
    class Meta:
        verbose_name = 'Student'  # display name
        verbose_name_plural = 'Studenten'  # plural display name

    matriculation_number = models.PositiveIntegerField(primary_key=True, verbose_name='Matrikelnummer')
    name = models.CharField(max_length=200, verbose_name='Name')
    birthday = models.DateField(verbose_name='Geburtsdatum')

    def get_absolute_url(self):
        """ tell Django how to calculate the canonical URL for an object """
        return reverse('studentmanager:student')

    def __str__(self):
        """ get string representation of the object for serialization """
        return str(self.matriculation_number)


class Exam(models.Model):
    class Meta:
        verbose_name = 'Prüfung'  # display name
        verbose_name_plural = 'Prüfungen'  # plural display name

    exam_id = models.PositiveIntegerField(primary_key=True, verbose_name='Prüfungsnummer')
    title = models.CharField(max_length=500, verbose_name='Titel')
    date = models.DateField(verbose_name='Datum')

    def __str__(self):
        """ get string representation of the object for serialization """
        return str(self.exam_id)


class Result(models.Model):
    # No student should be able to be deleted as long as there are still results to show.
    matriculation_number = models.ForeignKey(Student, on_delete=models.PROTECT, verbose_name='Matrikelnummer')

    # No student should be able to be deleted as long as there are still results to show.
    exam_id = models.ForeignKey(Exam, on_delete=models.PROTECT, verbose_name='Prüfungsnummer')
    grade = models.DecimalField(max_digits=3, decimal_places=2, default=None,
                                validators=[MaxValueValidator(6), MinValueValidator(1)],
                                verbose_name='Note')

    # Workaround for composite primary-key
    # Get Data using Result.objects.get(matriculation_number=”10”,exam_id=”125”)
    class Meta:
        unique_together = (('matriculation_number', 'exam_id'),)
        verbose_name = 'Ergebnis'
        verbose_name_plural = 'Ergebnisse'

    def __str__(self):
        """ get string representation of the object for serialization """
        return '{} - {}'.format(self.exam_id, self.matriculation_number)

studentmanager/forms.py
"""
Collection of all custom created Forms to use in the Create and Delete View
"""

from django import forms

from .models import Student, Exam, Result


class CreateStudentForm(forms.ModelForm):
    class Meta:
        model = Student  # model to create
        fields = ['matriculation_number', 'name', 'birthday']  # visible form fields, use model attributes

        # specify the input types for each field to use form validation
        # use attrs to store css class for bootstrap
        widgets = {
            'matriculation_number': forms.NumberInput(attrs={'class': 'form-control'}),
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'birthday': forms.DateInput(attrs={'class': 'form-control'})
        }


class CreateExamForm(forms.ModelForm):
    class Meta:
        model = Exam  # model to create
        fields = ['exam_id', 'title', 'date']  # visible form fields, use model attributes

        # specify the input types for each field to use form validation
        # use attrs to store css class for bootstrap
        widgets = {
            'exam_id': forms.NumberInput(attrs={'class': 'form-control'}),
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'date': forms.DateInput(attrs={'class': 'form-control'})
        }


class CreateResultForm(forms.ModelForm):
    class Meta:
        model = Result  # model to create
        fields = ['exam_id', 'matriculation_number', 'grade']  # visible form fields, use model attributes

        # specify the input types for each field to use form validation
        # use attrs to store css class for bootstrap
        widgets = {
            'exam_id': forms.Select(choices=Exam.objects.all(), attrs={'class': 'form-control'}),
            'matriculation_number': forms.Select(choices=Student.objects.all(), attrs={'class': 'form-control'}),
            'grade': forms.NumberInput(attrs={'class': 'form-control'})
        }

studentmanager/views/exam.py
"""
Views related to Exam
"""

from django.db.models import ProtectedError
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views import generic

from studentmanager.forms import CreateExamForm
from studentmanager.models import Exam


class ExamListView(generic.ListView):
    queryset = Exam.objects.order_by('exam_id')  # get data for table
    template_name = 'studentmanager/exam/exam_list.html'  # template to render


class ExamCreateView(generic.CreateView):
    form_class = CreateExamForm  # form class to render in template
    template_name = 'studentmanager/exam/exam_create_form.html'  # template to render
    success_url = reverse_lazy('studentmanager:exam')  # redirect to url after creation


class ExamDeleteView(generic.DeleteView):
    model = Exam  # set model to delete
    template_name = 'studentmanager/exam/exam_confirm_delete.html'  # template to render
    success_url = reverse_lazy('studentmanager:exam')  # redirect to url after deletion

    def get_object(self):
        """get exam by exam_id using the ID URL parameter"""

        # extract exam_id from keyword-arguments to use as primary key
        _exam_id = self.kwargs.get('id')

        # try to get exam by exam_id or raise 404 Error
        return get_object_or_404(Exam, exam_id=_exam_id)

    def delete(self, request, *args, **kwargs):
        """try to delete the exam + redirect to success_url or catch error message and return to form"""

        self.object = self.get_object()
        success_url = self.get_success_url()
        try:
            self.object.delete()
            # Redirect to success_url
            return HttpResponseRedirect(success_url)
        except ProtectedError:
            # add error object to context
            context = self.get_context_data(
                object=self.object,
                error='Prüfung konnte nicht gelöscht werden, da noch Ergebnisse für diese eingetragen sind!'
            )
            # stay on the confirm_error page and show error
            return self.render_to_response(context)

studentmanager/views/result.py
"""
Views related to Result
"""

from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views import generic

from studentmanager.forms import CreateResultForm
from studentmanager.models import Result


class ResultListView(generic.ListView):
    queryset = Result.objects.order_by('exam_id')  # get data for table
    template_name = 'studentmanager/result/result_list.html'  # template to render


class ResultCreateView(generic.CreateView):
    form_class = CreateResultForm  # form class to render in template
    template_name = 'studentmanager/result/result_create_form.html'  # template to render
    success_url = reverse_lazy('studentmanager:result')  # redirect to url after creation


class ResultDeleteView(generic.DeleteView):
    model = Result  # set model to delete
    template_name = 'studentmanager/result/result_confirm_delete.html'  # template to render
    success_url = reverse_lazy('studentmanager:result')  # redirect to url after creation

    def get_object(self):
        """get result by exam_id and matriculation using the exam_id and student_id URL parameter"""

        # extract the exam_id and student_id from the keyword-arguments to use them as query parameters
        _exam_id = self.kwargs.get('exam_id')
        _matriculation_number = self.kwargs.get('student_id')

        # try to get the result by exam_id and matriculation_number or raise Error 404.
        return get_object_or_404(Result, exam_id=_exam_id, matriculation_number=_matriculation_number)

studentmanager/views/student.py
"""
Views related to Student
"""

from django.db.models import ProtectedError
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views import generic

from studentmanager.forms import CreateStudentForm
from studentmanager.models import Student


class StudentListView(generic.ListView):
    queryset = Student.objects.order_by('matriculation_number')  # get data for table
    template_name = 'studentmanager/student/student_list.html'  # template to render


class StudentCreateView(generic.CreateView):
    form_class = CreateStudentForm  # form class to render in template
    template_name = 'studentmanager/student/student_create_form.html'  # template to render
    success_url = reverse_lazy('studentmanager:student')  # redirect to url after creation


class StudentDeleteView(generic.DeleteView):
    model = Student  # set model to delete
    template_name = 'studentmanager/student/student_confirm_delete.html'  # template to render
    success_url = reverse_lazy('studentmanager:student')  # redirect to url after deletion

    def get_object(self):
        """get student by matriculation_number using the ID URL parameter"""

        # extract the matriculation of a student from the keywordarguments to use as primary key
        _matriculation_number = self.kwargs.get('id')

        # try to get student by PK or raise Error 404
        return get_object_or_404(Student, matriculation_number=_matriculation_number)

    def delete(self, request, *args, **kwargs):
        """try to delete the student + redirect to success_url or catch error message and return to form"""

        self.object = self.get_object()  # get object to be deleted
        success_url = self.get_success_url()

        try:
            self.object.delete()

            # Redirect to success_url
            return HttpResponseRedirect(success_url)
        except ProtectedError:
            # add error object to context
            context = self.get_context_data(
                object=self.object,
                error='Student konnte nicht gelöscht werden, da noch Ergebnisse für ihn eingetragen sind!'
            )

            # stay on the confirm_error page and show error
            return self.render_to_response(context)

templates/studentmanager/create_exam_form.html
{% extends 'studentmanager/index.html' %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <form class="form-vertical" action="" method="post" enctype="multipart/form-data"
                              autocomplete="on">
                            {% csrf_token %}
                            {% include 'studentmanager/form-template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <div class="btn-group">
                                        <button type="submit" class="btn btn-primary"><i class="fas fa-save"></i>
                                            Speichern
                                        </button>
                                        <a href="{% url 'studentmanager:exam' %}" class="btn btn-default"><i
                                                class="fas fa-times"></i> Abbrechen</a>
                                    </div>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/studentmanager/exam_confirm_delete.html
{% extends 'studentmanager/index.html' %}

{% block content %}
    <form action="." method="post">
        {% csrf_token %}
        <h1>Prüfung "{{ object.exam_id }} - {{ object.title }}" endgültig löschen?</h1>
        <p>
        <div class="btn-group">
            <button type="submit" class="btn btn-primary"><i class="fas fa-check"></i> Ja</button>
            <a href="{% url 'studentmanager:exam' %}" class="btn btn-default"><i class="fas fa-times"></i> Abbrechen</a>
        </div>
        </p>
    </form>
{% endblock %}

templates/studentmanager/footbar.html
<footer class="footer custom-footer bg-light">
    <!-- Copyright -->
    <div class="footer-copyright text-center py-3 sticky-bottom">© 2019 Copyright:
        <a href="https://www.youtube.com/watch?v=u8qgehH3kEQ">Benedikt Grimmeisen & Stefanie Scholtz</a>
    </div>
</footer>

templates/studentmanager/form-template.html
{% for error in form.non_field_errors %}
    <div class="form-group">
        <div class="alert alert-danger col-sm-10" role="alert">
            <strong>Fehler!</strong> {{ error }}
        </div>
    </div>
{% endfor %}
{% for field in form %}
    <div class="form-group">
        {% for field_error in field.errors %}
            <div class="form-group">
                <div class="alert alert-danger col-sm-10" role="alert">
                    <strong>Fehler!</strong> {{ field_error }}
                </div>
            </div>
        {% endfor %}
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <label class="col-sm-10">{{ field }}</label>
    </div>
{% endfor %}

templates/studentmanager/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Studenten Manager v0.1</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css">
    <link rel="stylesheet" type="text/css" href="{% static 'studentmanager/css/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <script src="{% static 'studentmanager/js/tooltip.js' %}"></script>
    <link rel="shortcut icon" type="image/png" href="{% static 'studentmanager/img/favicon.ico' %}"/>
</head>

<body>
    <!--Navbar Area-->
    {% include 'studentmanager/navbar.html' %}

    <!--Content Area -->
    <main role="main" class="container-fluid">
        {% block content %}
        {% endblock %}
    </main>

    <!-- Footer -->
    {% include 'studentmanager/footbar.html' %}
</body>
</html>

templates/studentmanager/landingpage.html
{% extends 'studentmanager/index.html' %}
{% load static %}

{% block content %}
    {% if user.is_authenticated %}
        <!-- simple dashboard -->
        <div class="container">
                <div class="row">
                <div class="col-md-12">
                    <h1 class="display-4">Dashboard</h1>
                </div>
            </div>
            <div class="row">
                {% for element in data %}
                    <div class="col-md-4">
                        <div class="card text-center" >
                            <div class="card-header">{{ element.label }}</div>
                            <div class="card-body">
                                <p class="card-text display-1">{{ element.count }}</p>
                                <hr/>
                                <p class="card-text"><strong>Durchschnitt:</strong> {{ element.average | floatformat:2 }} </p>
                                <p class="card-text"><strong>Bester Schnitt:</strong> {{ element.best | floatformat:2 }}</p>
                                <p class="card-text"><strong>Schlechtester Schnitt:</strong> {{ element.worst| floatformat:2 }}</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% else %}
        <!-- landing page -->
        <div class="jumbotron">
          <h1 class="display-4">Student Manager v0.1</h1>
          <p class="lead">Herzlich Willkommen beim Pilotprojekt des neuen Notenverwaltungstool der Hochschule Aalen.</p>
          <hr class="my-4">
          <p>Um Daten der Studierenden einsehen oder verändern zu können, melden sie sich bitte zuerst an.</p>
          <p class="lead">
              <a href="{% url 'studentmanager:login' %}" class="btn btn-primary btn-lg"><i
                            class="fas fa-sign-in-alt"></i> Zur Anmeldung</a></li>
          </p>
        </div>
    {% endif %}
{% endblock content %}

templates/studentmanager/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'studentmanager:index' %}">Student Manager v0.1</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'studentmanager:student' %}">Studenten<span
                        class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'studentmanager:exam' %}">Prüfungen</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'studentmanager:result' %}">Ergebnisse</a>
            </li>

        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li class="nav-item">
                {% if user.is_authenticated %}
                    <li class="pr-3 text-muted"><i class="fas fa-user"></i> {{ user.username }}</li>
                    <li><a href="{% url 'studentmanager:logout' %}" class="text-danger"><i
                            class="fas fa-sign-out-alt"></i> Logout</a></li>
                {% else %}
                    <li><a href="{% url 'studentmanager:login' %}" class="text-primary"><i
                            class="fas fa-sign-in-alt"></i> Login</a></li>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>

templates/studentmanager/student_confirm_delete.html
{% extends 'studentmanager/index.html' %}

{% block content %}
    <form action="." method="post">
        {% csrf_token %}
        <h1>Student "{{ object.matriculation_number }} - {{ object.name }}" endgültig löschen?</h1>
        <p>
        <div class="btn-group">
            <button type="submit" class="btn btn-primary"><i class="fas fa-check"></i> Ja</button>
            <a href="{% url 'studentmanager:student' %}" class="btn btn-default"><i class="fas fa-times"></i> Abbrechen</a>
        </div>
        </p>
    </form>
{% endblock %}

templates/studentmanager/student_form.html
{% extends 'studentmanager/index.html' %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <form class="form-vertical" action="" method="post" enctype="multipart/form-data" autocomplete="on">
                            {% csrf_token %}
                            {% include 'studentmanager/form-template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <div class="btn-group">
                                        <button type="submit" class="btn btn-primary"><i class="fas fa-save"></i>
                                            Speichern
                                        </button>
                                        <a href="{% url 'studentmanager:student' %}" class="btn btn-default"><i
                                                class="fas fa-times"></i> Abbrechen</a>
                                    </div>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}